// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tckcucleodrdxzjjtcty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRja2N1Y2xlb2RyZHh6amp0Y3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzY2NjYsImV4cCI6MjA2ODA1MjY2Nn0.AnpKKxnC6EvTBvb0MxhTq1enocrJ_CFQu2A1exf_HIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});